name: CI/CD
on:
  push:
    branches: [ master ]  
jobs:
  test:
    runs-on: we
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: get node version
        run:  node -v  
#       - name: Install dependencies
#         run: npm install      
       

