name: CI/CD
on:
  push:
    branches: [ master ]  
jobs:
  test:
    runs-on: we
    steps:
      - name: step 1
        run: echo Hello, world!
      - name: step 2
        run: ping 192.168.31.31 -c 2 -w 3
      - name: step 3
        run:  echo end
